import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:convert';

void main()=> runApp(MaterialApp(debugShowCheckedModeBanner:false, home: LoginScreen()));

class LoginScreen extends StatefulWidget{ @override State<LoginScreen> createState()=> _L(); }
class _L extends State<LoginScreen>{
  final c=TextEditingController(); String sp="1234";
  void initState(){ super.initState(); SharedPreferences.getInstance().then((p)=> setState(()=> sp=p.getString('app_password')??"1234")); }
  Widget build(BuildContext b){ return Scaffold(backgroundColor:Color(0xFF2E7D32),body:Center(child:Card(margin:EdgeInsets.all(24),child:Padding(padding:EdgeInsets.all(22),child:Column(mainAxisSize:MainAxisSize.min,children:[
    Icon(Icons.apartment,size:60,color:Color(0xFF2E7D32)),SizedBox(height:10),Text("Estate Management",style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),SizedBox(height:20),
    TextField(controller:c,obscureText:true,decoration:InputDecoration(labelText:"Password",border:OutlineInputBorder(),prefixIcon:Icon(Icons.lock))),SizedBox(height:15),
    SizedBox(width:double.infinity,height:45,child:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:Color(0xFF2E7D32)),onPressed:()async{var p=await SharedPreferences.getInstance();String r=p.getString('app_password')??"1234";if(c.text==r)Navigator.pushReplacement(b,MaterialPageRoute(builder:(_)=>Home()));else ScaffoldMessenger.of(b).showSnackBar(SnackBar(content:Text("Wrong! Default 1234")));},child:Text("LOGIN",style:TextStyle(color:Colors.white)))),SizedBox(height:8),Text("Default: 1234",style:TextStyle(fontSize:11,color:Colors.grey))
  ]))))); }
}

class Home extends StatefulWidget{ @override State<Home> createState()=> _H(); }
class _H extends State<Home>{
  int i=0; String en="Egbegabriel Estate"; List props=[]; List tens=[]; List pays=[];
  void initState(){super.initState(); _load();}
  _load()async{var p=await SharedPreferences.getInstance();setState((){en=p.getString('estate_name')??"Egbegabriel Estate"; props=jsonDecode(p.getString('props')??"[]"); tens=jsonDecode(p.getString('tens')??"[]"); pays=jsonDecode(p.getString('pays')??"[]");});}
  _save()async{var p=await SharedPreferences.getInstance(); await p.setString('estate_name',en); await p.setString('props',jsonEncode(props)); await p.setString('tens',jsonEncode(tens)); await p.setString('pays',jsonEncode(pays));}
  _editE(){var cc=TextEditingController(text:en); showDialog(context:context,builder:(_)=>AlertDialog(title:Text("Editable Estate Name"),content:TextField(controller:cc,decoration:InputDecoration(border:OutlineInputBorder(),labelText:"Estate Name")),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:Text("Cancel")),ElevatedButton(onPressed:(){setState(()=>en=cc.text); _save(); Navigator.pop(context);},child:Text("Save"))]));}
  _addP(){var cc=TextEditingController(); showDialog(context:context,builder:(_)=>AlertDialog(title:Text("Add Property"),content:TextField(controller:cc,decoration:InputDecoration(labelText:"Property Name",border:OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:Text("Cancel")),ElevatedButton(onPressed:(){setState(()=>props.add({"name":cc.text,"d":DateTime.now().toString().substring(0,10)})); _save(); Navigator.pop(context);},child:Text("Add"))]));}
  _addT(){var n=TextEditingController(); var ph=TextEditingController(); var pl=TextEditingController(); var pu=TextEditingController(); var se=TextEditingController(); var de=TextEditingController(); var du=TextEditingController();
    showDialog(context:context,builder:(_)=>AlertDialog(title:Text("Add Tenant - All Charges"),content:SingleChildScrollView(child:Column(children:[
      TextField(controller:n,decoration:InputDecoration(labelText:"Tenant Name",border:OutlineInputBorder())),SizedBox(height:8),
      TextField(controller:ph,decoration:InputDecoration(labelText:"Phone",border:OutlineInputBorder())),SizedBox(height:8),
      TextField(controller:pl,decoration:InputDecoration(labelText:"Plot No",border:OutlineInputBorder())),SizedBox(height:12),
      Text("PURCHASE, SECURITY, DEVELOPMENT, ESTATE DUE (₦)",style:TextStyle(fontWeight:FontWeight.bold,fontSize:11)),SizedBox(height:8),
      TextField(controller:pu,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:"Purchase",border:OutlineInputBorder())),SizedBox(height:8),
      TextField(controller:se,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:"Security",border:OutlineInputBorder())),SizedBox(height:8),
      TextField(controller:de,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:"Development",border:OutlineInputBorder())),SizedBox(height:8),
      TextField(controller:du,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:"Estate Due",border:OutlineInputBorder())),
    ])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:Text("Cancel")),ElevatedButton(onPressed:(){double a=double.tryParse(pu.text)??0,b=double.tryParse(se.text)??0,c=double.tryParse(de.text)??0,d=double.tryParse(du.text)??0,tt=a+b+c+d; setState(()=>tens.add({"name":n.text,"phone":ph.text,"plot":pl.text,"pur":a,"sec":b,"dev":c,"due":d,"tot":tt,"paid":0.0,"bal":tt})); _save(); Navigator.pop(context);},child:Text("Save"))]));}
  _det(int idx){var t=tens[idx]; var pc=TextEditingController(); showModalBottomSheet(context:context,isScrollControlled:true,builder:(_)=>Padding(padding:EdgeInsets.fromLTRB(15,15,15,MediaQuery.of(context).viewInsets.bottom+15),child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
    Center(child:Container(width:40,height:4,color:Colors.grey)),SizedBox(height:12),Text(t['name'],style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),Text("Phone:${t['phone']} | Plot:${t['plot']}"),Divider(),
    Text("TENANTS MENU CHARGES",style:TextStyle(fontWeight:FontWeight.bold,color:Color(0xFF2E7D32))),Text("Purchase: ₦${t['pur']}\nSecurity: ₦${t['sec']}\nDevelopment: ₦${t['dev']}\nEstate Due: ₦${t['due']}"),SizedBox(height:8),
    Container(width:double.infinity,padding:EdgeInsets.all(12),decoration:BoxDecoration(color:Color(0xFFE8F5E9),borderRadius:BorderRadius.circular(8)),child:Text("TOTAL: ₦${t['tot']}\nPAID: ₦${t['paid']}\nBALANCE: ₦${t['bal']}",style:TextStyle(fontWeight:FontWeight.bold,color:Color(0xFF2E7D32)))),
    SizedBox(height:12),TextField(controller:pc,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:"Installmental Payment",border:OutlineInputBorder(),prefixText:"₦ ")),SizedBox(height:8),
    SizedBox(width:double.infinity,child:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:Color(0xFF2E7D32)),onPressed:(){double a=double.tryParse(pc.text)??0; if(a<=0)return; setState((){tens[idx]['paid']+=a; tens[idx]['bal']=tens[idx]['tot']-tens[idx]['paid']; pays.add({"ten":t['name'],"amt":a,"date":DateTime.now().toString().substring(0,16),"plot":t['plot']});}); _save(); Navigator.pop(context);},child:Text("Add Installment",style:TextStyle(color:Colors.white)))),
    SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton.icon(icon:Icon(Icons.receipt),label:Text("Receipt"),onPressed:(){showDialog(context:context,builder:(_)=>AlertDialog(title:Text("$en\nRECEIPT"),content:Text("Tenant:${t['name']}\nPlot:${t['plot']}\nPhone:${t['phone']}\nDate:${DateTime.now().toString().substring(0,10)}\n\nPurchase:₦${t['pur']}\nSecurity:₦${t['sec']}\nDev:₦${t['dev']}\nEstate Due:₦${t['due']}\n-----\nTotal:₦${t['tot']}\nPaid:₦${t['paid']}\nBal:₦${t['bal']}\n\nThanks!\n$en"),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:Text("Close"))]));})),SizedBox(width:8),Expanded(child:OutlinedButton.icon(icon:Icon(Icons.notifications_active),label:Text("Alert"),onPressed:(){var mc=TextEditingController(text:"Hello ${t['name']}, this is $en. Your balance ₦${t['bal']} for Plot ${t['plot']}. Purchase ₦${t['pur']}, Sec ₦${t['sec']}, Dev ₦${t['dev']}, Due ₦${t['due']}. Please pay. Thanks."); showDialog(context:context,builder:(_)=>AlertDialog(title:Text("Instant Tenant Alert"),content:TextField(controller:mc,maxLines:5,decoration:InputDecoration(border:OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:Text("Cancel")),ElevatedButton(onPressed:(){Navigator.pop(context); ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("Alert ready for ${t['phone']}")) );},child:Text("Send"))]));}))])
  ])))));}
  Widget qk(IconData ic,String lb,VoidCallback f){return GestureDetector(onTap:f,child:Container(height:95,decoration:BoxDecoration(border:Border.all(color:Colors.grey.shade300),borderRadius:BorderRadius.circular(12),color:Colors.white),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(ic,color:Color(0xFF2E7D32)),SizedBox(height:6),Text(lb,textAlign:TextAlign.center,style:TextStyle(fontSize:12))])));}
  Widget build(BuildContext context){
    Widget b;
    if(i==0){ b=SingleChildScrollView(padding:EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
      GestureDetector(onTap:_editE,child:Container(width:double.infinity,padding:EdgeInsets.all(20),decoration:BoxDecoration(color:Color(0xFF2E7D32),borderRadius:BorderRadius.circular(16)),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text("Total Properties",style:TextStyle(color:Colors.white70,fontSize:13)),Text("${props.length}",style:TextStyle(color:Colors.white,fontSize:36,fontWeight:FontWeight.bold)),SizedBox(height:6),Row(children:[Text(en,style:TextStyle(color:Colors.white,fontWeight:FontWeight.bold,fontSize:13)),SizedBox(width:4),Icon(Icons.edit,size:14,color:Colors.white70)])]),Icon(Icons.apartment,size:48,color:Colors.white)]))),
      SizedBox(height:20),Text("Quick Actions",style:TextStyle(fontWeight:FontWeight.bold,fontSize:16)),SizedBox(height:12),
      Row(children:[Expanded(child:qk(Icons.add_home_work,"Add\nProperty",_addP)),SizedBox(width:10),Expanded(child:qk(Icons.people,"Tenants",(){setState(()=>this.i=1);})),SizedBox(width:10),Expanded(child:qk(Icons.receipt_long,"Payments",(){setState(()=>this.i=1);} )) ] ),
      SizedBox(height:20),Text("Recent Tenants",style:TextStyle(fontWeight:FontWeight.bold)),
     ...tens.take(5).map((t)=>Card(child:ListTile(title:Text(t['name'],style:TextStyle(fontWeight:FontWeight.bold)),subtitle:Text("Plot ${t['plot']} Bal ₦${t['bal']}"),trailing:Icon(Icons.arrow_forward_ios,size:14),onTap:()=>_det(tens.indexOf(t))))).toList()
    ]));}
    else if(i==1){ b=Column(children:[Padding(padding:EdgeInsets.all(12),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text("Properties / Tenants (${tens.length})",style:TextStyle(fontWeight:FontWeight.bold,fontSize:16)),ElevatedButton(onPressed:_addT,child:Text("+ Add"))])), Expanded(child:tens.isEmpty?Center(child:Text("No tenant. Add with Purchase, Security, Dev, Estate Due")):ListView.builder(itemCount:tens.length,itemBuilder:(_,k){var t=tens[k];return Card(margin:EdgeInsets.symmetric(horizontal:10,vertical:5),child:ListTile(title:Text(t['name'],style:TextStyle(fontWeight:FontWeight.bold)),subtitle:Text("Plot:${t['plot']} | P:₦${t['pur']} S:₦${t['sec']} D:₦${t['dev']} E:₦${t['due']}\nTot ₦${t['tot']} Paid ₦${t['paid']} Bal ₦${t['bal']}"),isThreeLine:true,onTap:()=>_det(k),trailing:Icon(Icons.more_vert)));}))]);}
    else{ var pc=TextEditingController(); var ec=TextEditingController(text:en); b=SingleChildScrollView(padding:EdgeInsets.all(16),child:Column(children:[Icon(Icons.person_pin,size:70,color:Color(0xFF2E7D32)),Text(en,style:TextStyle(fontWeight:FontWeight.bold,fontSize:18)),SizedBox(height:20), TextField(controller:ec,decoration:InputDecoration(labelText:"Editable Estate Name",border:OutlineInputBorder(),prefixIcon:Icon(Icons.edit))),SizedBox(height:10),SizedBox(width:double.infinity,child:ElevatedButton(onPressed:(){setState(()=>en=ec.text); _save(); ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("Updated")));},child:Text("Update Name"))),Divider(height:30),TextField(controller:pc,decoration:InputDecoration(labelText:"Changeable Password - New",border:OutlineInputBorder(),prefixIcon:Icon(Icons.lock))),SizedBox(height:10),SizedBox(width:double.infinity,child:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:Color(0xFF2E7D32)),onPressed:()async{var p=await SharedPreferences.getInstance(); await p.setString('app_password',pc.text); ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("Password changed to ${pc.text}")));},child:Text("Change Password",style:TextStyle(color:Colors.white)))),SizedBox(height:25),OutlinedButton.icon(icon:Icon(Icons.logout),label:Text("Logout"),onPressed:()=>Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>LoginScreen()))) ]));}
    return Scaffold(appBar:AppBar(title:Text("Estate Management"),backgroundColor:Color(0xFF2E7D32),foregroundColor:Colors.white),body:b,bottomNavigationBar:BottomNavigationBar(currentIndex:i,selectedItemColor:Color(0xFF2E7D32),onTap:(x)=>setState(()=>i=x),items:[BottomNavigationBarItem(icon:Icon(Icons.dashboard),label:"Dashboard"),BottomNavigationBarItem(icon:Icon(Icons.home_work),label:"Properties"),BottomNavigationBarItem(icon:Icon(Icons.person),label:"Profile")]),floatingActionButton:i==0?FloatingActionButton(backgroundColor:Color(0xFF2E7D32),onPressed:_addP,child:Icon(Icons.add,color:Colors.white)):FloatingActionButton(backgroundColor:Color(0xFF2E7D32),onPressed:_addT,child:Icon(Icons.person_add,color:Colors.white)));
  }
}
